### ISSUE TITLE
V1.3 não está disponível

### ISSUE THREAD

**Issue by davibc19** [ChristopherPablo/Trabalho-Adler#3]
Christopher fez o "upload" da versão 1.3. Entretanto, quando o Pedro fez o commit e o push do repositório local dele para o repositório do Github, a pasta 1.3 desapareceu.

Portanto, peço que atualize seu repositório local e faça o "upload" da V1.3 novamente. Grato

**Comment by ChristopherPablo** [comment]
Atulização feita e a pasta da versão 1.3 foi reposta juntamente com todos os arquivos atualizados e as versões previas e posteriores!
