### ISSUE TITLE
Problemas com a versão V1.5 

### ISSUE THREAD

**Issue by ChristopherPablo** [ChristopherPablo/Trabalho-Adler#4]
A versão V1.5 está sofrendo uma incompatibilidade com as versões anteriores, o bug encontrado se apresenta na sincronização com o banco de dados usado, assim peço que dê uma olhada mais profunda e reverta o novo codigo apresentado para a sincronização anterior já usada, obrigado!

**Comment by davibc19** [comment]
Conforme solicitado a correção da incompatibilidade já foi feita. Peço que faça o "Pull" dos dados e verifique se está tudo certo agora. Se estiver, já podemos fechar este Issue. 

Agradeço.

**Comment by ChristopherPablo** [comment]
Tudo funcionando perfeitamente, o problema foi resolvido, Obrigado pela eficiência! Podemos fechar o Issue.
